from dataclasses import dataclass
from test.pycardano.util import check_two_way_cbor
from typing import Union

from pycardano.plutus import ExecutionUnits, PlutusData, Redeemer, RedeemerTag


@dataclass
class MyTest(PlutusData):
    CONSTR_ID = 130

    a: int
    b: bytes


@dataclass
class BigTest(PlutusData):
    CONSTR_ID = 8

    test: MyTest


@dataclass
class LargestTest(PlutusData):
    CONSTR_ID = 9


@dataclass
class VestingParam(PlutusData):
    CONSTR_ID = 1

    beneficiary: bytes
    deadline: int
    testa: Union[BigTest, LargestTest]
    testb: Union[BigTest, LargestTest]


@dataclass
class MyRedeemer(Redeemer):
    data: MyTest


def test_plutus_data():
    """Ground truth of this test is generated by test/resources/haskell/PlutusData. See its README for more details."""
    key_hash = bytes.fromhex("c2ff616e11299d9094ce0a7eb5b7284b705147a822f4ffbd471f971a")
    deadline = 1643235300000
    testa = BigTest(MyTest(123, b"1234"))
    testb = LargestTest()

    my_vesting = VestingParam(
        beneficiary=key_hash, deadline=deadline, testa=testa, testb=testb
    )
    assert (
        "d87a9f581cc2ff616e11299d9094ce0a7eb5b7284b705147a822f4ffbd471f971a1b0000017e9874d2a0d905019fd8668218829f187b4431323334ffffd9050280ff"
        == my_vesting.to_cbor()
    )
    check_two_way_cbor(my_vesting)


def test_redeemer():
    data = MyTest(123, b"234")
    redeemer = MyRedeemer(RedeemerTag.SPEND, 0, data, ExecutionUnits(1000000, 1000000))
    assert (
        "840000d8668218829f187b43323334ff821a000f42401a000f4240" == redeemer.to_cbor()
    )
    check_two_way_cbor(redeemer)
